/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ui;

import br.com.classes.Mapa;
import br.com.interfaces.FuncaoActionPerformed;

import java.awt.*;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.*;

/**
 *
 * @author Thiago
 */
public class DisplayMapa extends javax.swing.JPanel {
    
    private Mapa mapa;
    private FuncaoActionPerformed removerAcao;
    
    public DisplayMapa(Mapa mapa) {
        
        this.mapa = mapa;
        
        initComponents();
        customInitComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mapaNomeLabel = new javax.swing.JLabel();
        mapaNome = new javax.swing.JLabel();
        mapaDisplay = new javax.swing.JLabel();
        mapaRemoverBotao = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        mapaNomeLabel.setText("Nome: ");

        mapaDisplay.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        mapaDisplay.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                mapaDisplayMousePressed(evt);
            }
        });

        mapaRemoverBotao.setText("Remover");
        mapaRemoverBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mapaRemoverBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mapaDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jSeparator1)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(mapaRemoverBotao, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(mapaNomeLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(mapaNome, javax.swing.GroupLayout.DEFAULT_SIZE, 296, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(mapaNomeLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(mapaNome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapaDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(mapaRemoverBotao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void mapaRemoverBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mapaRemoverBotaoActionPerformed
        this.removerAcao.actionPerformed();
    }//GEN-LAST:event_mapaRemoverBotaoActionPerformed

    private void mapaDisplayMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_mapaDisplayMousePressed
        //Vai exibir a imagem em tamanho maior em uma nova janela
        //A janela somente exibirá a imagem.
        //A imagem estará dentro de um JScrollPane.
        //O endereço da imagem é o mesmo do mapa

        File file = new File(this.mapa.getEndereco());
        JFrame janela = new JFrame(this.mapa.getNome());
        janela.setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        janela.setSize(800, 600);
        janela.setResizable(true);
        janela.setLocationRelativeTo(null);
        janela.setLayout(new BorderLayout());


        JLabel label = new JLabel();
        label.setIcon(new ImageIcon(file.getAbsolutePath()));
        JScrollPane scroll = new JScrollPane(label);

        Rectangle bounds = scroll.getViewport().getViewRect();
        Dimension size = scroll.getViewport().getViewSize();
        int x = (size.width - bounds.width) / 2;
        int y = (size.height - bounds.height) / 2;
        scroll.getViewport().setViewPosition(new Point(x, y));

        janela.add(scroll, BorderLayout.CENTER);
        janela.setVisible(true);

    }//GEN-LAST:event_mapaDisplayMousePressed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel mapaDisplay;
    private javax.swing.JLabel mapaNome;
    private javax.swing.JLabel mapaNomeLabel;
    private javax.swing.JButton mapaRemoverBotao;
    // End of variables declaration//GEN-END:variables

    private void customInitComponents() {
        mapaNome.setText(mapa.getNome());
        
        BufferedImage imagem = null;
        try{
            imagem = ImageIO.read(new File (mapa.getEndereco()));
            Image mapaImagem = imagem.getScaledInstance(342, 266, Image.SCALE_SMOOTH);
            mapaDisplay.setIcon(new ImageIcon(mapaImagem));
        }catch(IOException|NullPointerException e){
           e.printStackTrace();
        }
                
    }
    
    public void setRemoverAcao(FuncaoActionPerformed removerAcao) {
        this.removerAcao = removerAcao;
    }
}
