/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ui;

import br.com.classes.Acao;
import br.com.classes.NpcDnd;
import br.com.classes.PericiaDnd;
import br.com.classes.SalvamentoDnd;
import br.com.interfaces.FuncaoActionPerformed;

/**
 *
 * @author gfreitash
 */
public class DisplayNpc extends javax.swing.JPanel {

    private NpcDnd npc;
    private FuncaoActionPerformed editarAcao;
    private FuncaoActionPerformed removerAcao;

    /**
     * Creates new form DisplayNpc
     */
    public DisplayNpc(NpcDnd npc) {
        initComponents();

        this.npc = npc;
        this.npcNomeTextField.setText(npc.getNome());
        this.npcClasseDificuldadeTextField.setText(String.valueOf(npc.getClasseDificuldade()));
        this.npcAlinhamentoComboBox.addItem(npc.getAlinhamento());
        this.npcAlinhamentoComboBox.setSelectedIndex(0);
        this.npcVelocidadeTextField.setText(String.valueOf(npc.getVelocidade()));
        this.npcClasseArmaduraTextField.setText(String.valueOf(npc.getClasseArmadura()));
        this.npcHitpointsTextField.setText(String.valueOf(npc.getHitPoints()));

        this.npcForcaSpinner.setValue(npc.getForca());
        this.npcDestrezaSpinner.setValue(npc.getDestreza());
        this.npcConstituicaoSpinner.setValue(npc.getConstituicao());
        this.npcInteligenciaSpinner.setValue(npc.getInteligencia());
        this.npcSabedoriaSpinner.setValue(npc.getSabedoria());
        this.npcCarismaSpinner.setValue(npc.getCarisma());

        for(Acao acao: npc.getAcoes()){
            ElementAcao elementAcao = new ElementAcao(acao.getNome(), acao.getDescricao());
            this.npcAcoesPanel.add(elementAcao);
        }

        for(SalvamentoDnd salvamento: npc.getSalvamentos()){
            ElementAtributo elementSalvamento = new ElementAtributo(salvamento.getAtributo(), salvamento.getModificador());
            this.npcSalvamentosPanel.add(elementSalvamento);
        }

        for(PericiaDnd pericia: npc.getPericias()){
            ElementAtributo elementPericia = new ElementAtributo(pericia.getPericia(), pericia.getModificador());
            this.npcPericiasPanel.add(elementPericia);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPanel = new javax.swing.JPanel();
        criarNpcMainPanel = new javax.swing.JPanel();
        npcNomeLabel = new javax.swing.JLabel();
        npcNomeTextField = new javax.swing.JTextField();
        npcVelocidadeTextField = new javax.swing.JTextField();
        npcVelocidadeLabel = new javax.swing.JLabel();
        npcClasseDificuldadeTextField = new javax.swing.JTextField();
        npcClasseDificuldadeLabel = new javax.swing.JLabel();
        npcAlinhamentoComboBox = new javax.swing.JComboBox<>();
        npcAlinhamentoLabel = new javax.swing.JLabel();
        npcHitpointsLabel = new javax.swing.JLabel();
        npcHitpointsTextField = new javax.swing.JTextField();
        npcClasseArmaduraTextField = new javax.swing.JTextField();
        npcClasseArmaduraLabel = new javax.swing.JLabel();
        npcForcaLabel = new javax.swing.JLabel();
        npcForcaSpinner = new javax.swing.JSpinner();
        npcConstituicaoSpinner = new javax.swing.JSpinner();
        npcConstituicaoLabel = new javax.swing.JLabel();
        npcInteligenciaSpinner = new javax.swing.JSpinner();
        npcInteligenciaLabel = new javax.swing.JLabel();
        npcSabedoriaSpinner = new javax.swing.JSpinner();
        npcSabedoriaLabel = new javax.swing.JLabel();
        npcCarismaSpinner = new javax.swing.JSpinner();
        npcCarismaLabel = new javax.swing.JLabel();
        npcAcoesLabel = new javax.swing.JLabel();
        npcAcoesScroolpane = new javax.swing.JScrollPane();
        npcAcoesPanel = new javax.swing.JPanel();
        npcSalvamentosScroolpane = new javax.swing.JScrollPane();
        npcSalvamentosPanel = new javax.swing.JPanel();
        npcSalvamentosLabel = new javax.swing.JLabel();
        npcPericiasScroolpane = new javax.swing.JScrollPane();
        npcPericiasPanel = new javax.swing.JPanel();
        npcPericiasLabel = new javax.swing.JLabel();
        npcDestrezaSpinner = new javax.swing.JSpinner();
        npcDestrezaLabel = new javax.swing.JLabel();
        editarBotao = new javax.swing.JButton();
        removerBotao = new javax.swing.JButton();

        setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        criarNpcMainPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        npcNomeLabel.setText("Nome:");

        npcNomeTextField.setEditable(false);
        npcNomeTextField.setEnabled(false);

        npcVelocidadeTextField.setEditable(false);
        npcVelocidadeTextField.setEnabled(false);

        npcVelocidadeLabel.setText("Velocidade:");

        npcClasseDificuldadeTextField.setEditable(false);
        npcClasseDificuldadeTextField.setEnabled(false);

        npcClasseDificuldadeLabel.setText("CD:");

        npcAlinhamentoComboBox.setEnabled(false);

        npcAlinhamentoLabel.setText("Alinhamento:");

        npcHitpointsLabel.setText("Hit Points:");

        npcHitpointsTextField.setEditable(false);
        npcHitpointsTextField.setEnabled(false);

        npcClasseArmaduraTextField.setEditable(false);
        npcClasseArmaduraTextField.setEnabled(false);

        npcClasseArmaduraLabel.setText("CA:");

        npcForcaLabel.setText("Força:");

        npcForcaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        npcForcaSpinner.setEnabled(false);

        npcConstituicaoSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        npcConstituicaoSpinner.setEnabled(false);

        npcConstituicaoLabel.setText("Constituição:");

        npcInteligenciaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        npcInteligenciaSpinner.setEnabled(false);

        npcInteligenciaLabel.setText("Inteligência:");

        npcSabedoriaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        npcSabedoriaSpinner.setEnabled(false);

        npcSabedoriaLabel.setText("Sabedoria:");

        npcCarismaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        npcCarismaSpinner.setEnabled(false);

        npcCarismaLabel.setText("Carisma:");

        npcAcoesLabel.setText("Ações:");

        npcAcoesScroolpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        npcAcoesPanel.setLayout(new javax.swing.BoxLayout(npcAcoesPanel, javax.swing.BoxLayout.Y_AXIS));
        npcAcoesScroolpane.setViewportView(npcAcoesPanel);

        npcSalvamentosScroolpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        npcSalvamentosPanel.setLayout(new javax.swing.BoxLayout(npcSalvamentosPanel, javax.swing.BoxLayout.Y_AXIS));
        npcSalvamentosScroolpane.setViewportView(npcSalvamentosPanel);

        npcSalvamentosLabel.setText("Salvamentos:");

        npcPericiasScroolpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        npcPericiasPanel.setLayout(new javax.swing.BoxLayout(npcPericiasPanel, javax.swing.BoxLayout.Y_AXIS));
        npcPericiasScroolpane.setViewportView(npcPericiasPanel);

        npcPericiasLabel.setText("Perícias:");

        npcDestrezaSpinner.setModel(new javax.swing.SpinnerNumberModel(0, 0, 30, 1));
        npcDestrezaSpinner.setEnabled(false);

        npcDestrezaLabel.setText("Destreza:");

        javax.swing.GroupLayout criarNpcMainPanelLayout = new javax.swing.GroupLayout(criarNpcMainPanel);
        criarNpcMainPanel.setLayout(criarNpcMainPanelLayout);
        criarNpcMainPanelLayout.setHorizontalGroup(
            criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                .addComponent(npcNomeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npcNomeTextField))
                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                .addComponent(npcHitpointsLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npcHitpointsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(152, 152, 152)
                                .addComponent(npcSalvamentosLabel)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(npcAlinhamentoLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npcAlinhamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(npcClasseDificuldadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npcClasseDificuldadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(npcVelocidadeLabel)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(npcVelocidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                .addGap(60, 60, 60)
                                .addComponent(npcPericiasLabel))))
                    .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(npcAcoesLabel, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(npcAcoesScroolpane, javax.swing.GroupLayout.PREFERRED_SIZE, 266, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criarNpcMainPanelLayout.createSequentialGroup()
                                .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                        .addComponent(npcClasseArmaduraLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(npcClasseArmaduraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                                .addComponent(npcForcaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(npcForcaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                                .addComponent(npcConstituicaoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(npcConstituicaoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                                                .addComponent(npcSabedoriaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(2, 2, 2)
                                                .addComponent(npcSabedoriaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(npcDestrezaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(npcInteligenciaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(npcCarismaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(2, 2, 2)
                                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(npcCarismaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(npcInteligenciaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(npcDestrezaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addGap(6, 6, 6)))
                        .addComponent(npcSalvamentosScroolpane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(npcPericiasScroolpane, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        criarNpcMainPanelLayout.setVerticalGroup(
            criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(npcNomeLabel)
                    .addComponent(npcNomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npcVelocidadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npcVelocidadeLabel)
                    .addComponent(npcClasseDificuldadeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npcClasseDificuldadeLabel)
                    .addComponent(npcAlinhamentoComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(npcAlinhamentoLabel))
                .addGap(18, 18, 18)
                .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npcHitpointsLabel)
                            .addComponent(npcHitpointsTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npcClasseArmaduraTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npcClasseArmaduraLabel))
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, criarNpcMainPanelLayout.createSequentialGroup()
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npcSalvamentosLabel)
                            .addComponent(npcPericiasLabel))
                        .addGap(6, 6, 6)))
                .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(npcPericiasScroolpane)
                    .addGroup(criarNpcMainPanelLayout.createSequentialGroup()
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(npcDestrezaLabel)
                                .addComponent(npcDestrezaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(npcForcaLabel)
                                .addComponent(npcForcaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npcConstituicaoLabel)
                            .addComponent(npcConstituicaoSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npcInteligenciaLabel)
                            .addComponent(npcInteligenciaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(criarNpcMainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(npcSabedoriaLabel)
                            .addComponent(npcSabedoriaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(npcCarismaLabel)
                            .addComponent(npcCarismaSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(npcAcoesLabel)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(npcAcoesScroolpane, javax.swing.GroupLayout.DEFAULT_SIZE, 127, Short.MAX_VALUE))
                    .addComponent(npcSalvamentosScroolpane))
                .addContainerGap())
        );

        javax.swing.GroupLayout contentPanelLayout = new javax.swing.GroupLayout(contentPanel);
        contentPanel.setLayout(contentPanelLayout);
        contentPanelLayout.setHorizontalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 852, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(criarNpcMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        contentPanelLayout.setVerticalGroup(
            contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(contentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(contentPanelLayout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(criarNpcMainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        editarBotao.setText("Editar");
        editarBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarBotaoActionPerformed(evt);
            }
        });

        removerBotao.setText("Remover");
        removerBotao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                removerBotaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(editarBotao)
                .addGap(18, 18, 18)
                .addComponent(removerBotao))
            .addComponent(contentPanel, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(editarBotao)
                    .addComponent(removerBotao))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void editarBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarBotaoActionPerformed
        this.editarAcao.actionPerformed();
    }//GEN-LAST:event_editarBotaoActionPerformed

    private void removerBotaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_removerBotaoActionPerformed
        this.removerAcao.actionPerformed();
    }//GEN-LAST:event_removerBotaoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel contentPanel;
    private javax.swing.JPanel criarNpcMainPanel;
    private javax.swing.JButton editarBotao;
    private javax.swing.JLabel npcAcoesLabel;
    private javax.swing.JPanel npcAcoesPanel;
    private javax.swing.JScrollPane npcAcoesScroolpane;
    private javax.swing.JComboBox<String> npcAlinhamentoComboBox;
    private javax.swing.JLabel npcAlinhamentoLabel;
    private javax.swing.JLabel npcCarismaLabel;
    private javax.swing.JSpinner npcCarismaSpinner;
    private javax.swing.JLabel npcClasseArmaduraLabel;
    private javax.swing.JTextField npcClasseArmaduraTextField;
    private javax.swing.JLabel npcClasseDificuldadeLabel;
    private javax.swing.JTextField npcClasseDificuldadeTextField;
    private javax.swing.JLabel npcConstituicaoLabel;
    private javax.swing.JSpinner npcConstituicaoSpinner;
    private javax.swing.JLabel npcDestrezaLabel;
    private javax.swing.JSpinner npcDestrezaSpinner;
    private javax.swing.JLabel npcForcaLabel;
    private javax.swing.JSpinner npcForcaSpinner;
    private javax.swing.JLabel npcHitpointsLabel;
    private javax.swing.JTextField npcHitpointsTextField;
    private javax.swing.JLabel npcInteligenciaLabel;
    private javax.swing.JSpinner npcInteligenciaSpinner;
    private javax.swing.JLabel npcNomeLabel;
    private javax.swing.JTextField npcNomeTextField;
    private javax.swing.JLabel npcPericiasLabel;
    private javax.swing.JPanel npcPericiasPanel;
    private javax.swing.JScrollPane npcPericiasScroolpane;
    private javax.swing.JLabel npcSabedoriaLabel;
    private javax.swing.JSpinner npcSabedoriaSpinner;
    private javax.swing.JLabel npcSalvamentosLabel;
    private javax.swing.JPanel npcSalvamentosPanel;
    private javax.swing.JScrollPane npcSalvamentosScroolpane;
    private javax.swing.JLabel npcVelocidadeLabel;
    private javax.swing.JTextField npcVelocidadeTextField;
    private javax.swing.JButton removerBotao;
    // End of variables declaration//GEN-END:variables

    public void setBotaoEditarActionPerformed(FuncaoActionPerformed funcao) {
        this.editarAcao = funcao;
    }

    public void setBotaoRemoverActionPerformed(FuncaoActionPerformed funcao) {
        this.removerAcao = funcao;
    }
}
