/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package br.com.ui;

import br.com.interfaces.FuncaoActionPerformed;
import javax.swing.JLabel;
import javax.swing.JTextArea;
import java.awt.*;

/**
 *
 * @author gfreitash
 */
public class ElementAcao extends javax.swing.JPanel {
    
    private FuncaoActionPerformed remover;
    /**
     * Creates new form ElementAcao
     */
    public ElementAcao(String nomeAcao, String descricaoAcao) {
        initComponents();

        this.nomeAcao.setText(nomeAcao);
        this.descricaoAcaoTextArea.setText(descricaoAcao);
        
        this.setMaximumSize(this.getPreferredSize());
        this.botaoRemover.setVisible(false);
    }

    public String getNome() {
        return nomeAcao.getText();
    }

    public String getDescricao() {
        return descricaoAcaoTextArea.getText();
    }
    
    public void setBotaoRemoverActionPerformed(FuncaoActionPerformed funcao) {
        this.remover = funcao;
    }

    public void setBotaoRemoverVisible(boolean visible) {
        this.botaoRemover.setVisible(visible);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        contentPane = new javax.swing.JPanel();
        nomeAcao = new javax.swing.JLabel();
        descricaoAcaoScroolpane = new javax.swing.JScrollPane();
        descricaoAcaoTextArea = new javax.swing.JTextArea();
        botaoRemover = new javax.swing.JButton();

        setBorder(javax.swing.BorderFactory.createEtchedBorder());

        nomeAcao.setFont(new java.awt.Font("Dialog", 1, 12)); // NOI18N
        nomeAcao.setText("nomeAcao:");

        descricaoAcaoScroolpane.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        descricaoAcaoTextArea.setEditable(false);
        descricaoAcaoTextArea.setColumns(20);
        descricaoAcaoTextArea.setLineWrap(true);
        descricaoAcaoTextArea.setRows(3);
        descricaoAcaoTextArea.setWrapStyleWord(true);
        descricaoAcaoScroolpane.setViewportView(descricaoAcaoTextArea);

        botaoRemover.setText("Remover");
        botaoRemover.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoRemoverActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout contentPaneLayout = new javax.swing.GroupLayout(contentPane);
        contentPane.setLayout(contentPaneLayout);
        contentPaneLayout.setHorizontalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addComponent(nomeAcao)
                .addGap(0, 0, Short.MAX_VALUE))
            .addComponent(descricaoAcaoScroolpane, javax.swing.GroupLayout.DEFAULT_SIZE, 259, Short.MAX_VALUE)
            .addComponent(botaoRemover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        contentPaneLayout.setVerticalGroup(
            contentPaneLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(contentPaneLayout.createSequentialGroup()
                .addComponent(nomeAcao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(descricaoAcaoScroolpane, javax.swing.GroupLayout.DEFAULT_SIZE, 82, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(botaoRemover, javax.swing.GroupLayout.PREFERRED_SIZE, 19, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(contentPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoRemoverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoRemoverActionPerformed
        this.remover.actionPerformed();
    }//GEN-LAST:event_botaoRemoverActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoRemover;
    private javax.swing.JPanel contentPane;
    private javax.swing.JScrollPane descricaoAcaoScroolpane;
    private javax.swing.JTextArea descricaoAcaoTextArea;
    private javax.swing.JLabel nomeAcao;
    // End of variables declaration//GEN-END:variables
}
